version: '3.8'

services:
  data-driven-collection:
    image: docker020510/data-driven-test-collection:1.3
    volumes:
      - ./Data-driven-collection/docker-results/newman:/app/results

services:
  generate-token-as-pre-req-collection:
    image: docker020510/generate-token-as-pre-requisite-coll-test:1.3
    volumes:
      - ./Generate-token-as-pre-req-collection/docker-results/newman:/app/results      